version: 0.5
# (You cannot specify both "os: linux" and "os: windows".)
os: linux
# os: windows
files:
  - source: /
    destination: /var/www/html
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: root
    group: root
    mode: 777
    type:
      - file
# If you are not running any commands on the Amazon EC2 instance, then remove
#   the "hooks" section altogether. A blank or incomplete "hooks" section
#   may cause associated deployments to fail.
hooks:
# For each deployment lifecycle event, specify multiple "location" entries
#   if you want to run multiple scripts during that event.
# You can specify "timeout" as the number of seconds to wait until failing the deployment
#   if the specified scripts do not run within the specified time limit for the
#   specified event. For example, 900 seconds is 15 minutes. If not specified,
#      timeout:
#      runas:
#    - location:
#      timeout:
#      runas:
# During the ApplicationStart deployment lifecycle event, run the commands
#   in the script specified in "location".
#    - location:
#      timeout:
